version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    network_mode: 'host'
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: localhost
            port: '5432'
            database: bootcamp
            user: postgres
            password: postgres
            migrations: true
